Avoid use of external "builtin"
modelica/ModelicaStandardLibrary pull request #3640
Opened 2020-10-03 05:59 UTC by henrikt-ma

As it has already been established that the Modelica language functions can be accessed using a fully qualified name (see `Modelica.ComplexMath`, there seems to be no reason to use the `external "builtin"` construct.  Further, the uses in `Modelica.Math` are probably the only uses in the entire world, so getting rid of these could help us clean up the Modelica language a bit.

2020-10-05 06:29 UTC, sjoelund reviewed
My concern is that there might be some case where this is not inlined, or is inlined later than usual, causing some model in some tool to fail. I guess direct calls to the functions may be fine, but calls to these functions from inside of other functions might not be covered? If it is accepted and issues are found, I would propose to revert this change. At least it should work in theory and it's easier to test it if it's pushed through...

2020-10-05 07:20 UTC, HansOlsson commented
> As it has already been established that the Modelica language functions can be accessed using a fully qualified name (see `Modelica.ComplexMath`, there seems to be no reason to use the `external "builtin"` construct. Further, the uses in `Modelica.Math` are probably the only uses in the entire world, so getting rid of these could help us clean up the Modelica language a bit.

To me another alternative that has some advantages would be to remove the sin, cos etc from the Modelica Language; so that Modelica.Math.sin would be the only way of calling it, and then it obviously has to be external. As far as I recall they were sort added as an unintended consequence and misunderstanding of something in some old version of Dymola. If we really dislike external "builtin" construct, and are willing to take a step back we could make them external "C".

The reason for this is that  an operator 'sin' or 'atan' outside of any package is problematic in terms of finding them, and also their documentation.

2020-10-05 07:34 UTC, henrikt-ma commented
> > As it has already been established that the Modelica language functions can be accessed using a fully qualified name (see `Modelica.ComplexMath`, there seems to be no reason to use the `external "builtin"` construct. Further, the uses in `Modelica.Math` are probably the only uses in the entire world, so getting rid of these could help us clean up the Modelica language a bit.
> 
> To me another alternative that has some advantages would be to remove the sin, cos etc from the Modelica Language; so that Modelica.Math.sin would be the only way of calling it, and then it obviously has to be external. As far as I recall they were sort added as an unintended consequence and misunderstanding of something in some old version of Dymola. If we really dislike external "builtin" construct, and are willing to take a step back we could make them external "C".
> 
> The reason for this is that an operator 'sin' or 'atan' outside of any package is problematic in terms of finding them, and also their documentation.

I thought we wanted these in the core language so that tools will be able to perform all sorts of symbolic manipulation on these that require exact understanding of what these functions are.  Functions that are special in this way should not have their home in the MSL, in my opinion.

2020-10-06 11:39 UTC, sjoelund commented
> I thought we wanted these in the core language so that tools will be able to perform all sorts of symbolic manipulation that require exact understanding of what these functions are. Functions that are special in this way should not have their home in the MSL, in my opinion.

To me, it would be more annoying if you had to depend on MSL, a large library and import sin explicitly in order to use it in a small example model. ModelicaReference or tool-specific help for the builtin operators should be sufficient.

2020-10-06 12:15 UTC, henrikt-ma commented
> > I thought we wanted these in the core language so that tools will be able to perform all sorts of symbolic manipulation that require exact understanding of what these functions are. Functions that are special in this way should not have their home in the MSL, in my opinion.
> 
> To me, it would be more annoying if you had to depend on MSL, a large library and import sin explicitly in order to use it in a small example model. ModelicaReference or tool-specific help for the builtin operators should be sufficient.

Sounds like we agree and in line with this PR.

2020-10-06 12:22 UTC, HansOlsson commented
> To me, it would be more annoying if you had to depend on MSL, a large library and import sin explicitly in order to use it in a small example model. ModelicaReference or tool-specific help for the builtin operators should be sufficient.

I'm not so concerned about such small models, but about having non-essential operations built in in the language since built-in operators follow different rules.
Obviously tools may have special handling of functions, but we don't want to restrict that for no good reason.

2020-10-06 12:31 UTC, henrikt-ma commented
> I'm not so concerned about such small models, but about having non-essential operations built in in the language since built-in operators follow different rules.

I think we need to be explicit about which differences that would be.

> Obviously tools may have special handling of functions, but we don't want to restrict that for no good reason.

I think we should avoid the need for tools to have special handling of certain functions in the MSL.  In the odd cases this is needed, I prefer the use of `ModelicaServices` for this over special tool hacks operating directly on the MSL functions.

2020-10-12 08:25 UTC, HansOlsson commented
> > I'm not so concerned about such small models, but about having non-essential operations built in in the language since built-in operators follow different rules.
> 
> I think we need to be explicit about which differences that would be.

Some of the differences are that:
* Functions with external "builtin" are declared with named arguments, whereas functions built into the language don't necessarily support named arguments (or defaults).
* Functions with external "builtin" look like other functions, allowing more consistent discovery and documentation (instead of having two different variants). That's the reason we in Dymola have worked to add packages for builtin functionality (not only for functions in the Modelica Language).

2020-10-12 10:27 UTC, HansOlsson requested changes
As indicated I would prefer if we replaced the current built-in `.sin` with `function sin=Modelica.Math.sin`, and kept these built-in (or instead of 'replaced' used it as the definition).

2020-10-13 11:23 UTC, henrikt-ma commented
> As indicated I would prefer if we replaced the current built-in `.sin` with `function sin=Modelica.Math.sin`, and kept these built-in (or instead of 'replaced' used it as the definition).

While I don't really see a problem with having `sin` and friends in the language specification (still with wrappers in `Modelica.Math`), there are several drawbacks of doing it the other way (as noted above):
- Functions like `sin` have more interesting relations to other core mathematical functions than what we can practically handle with generic annotations.  (Not counting introducing the annotation `MathFunction=sine` to express that this is precisely the sine function.)
- Basing the definition of `sin` on `Modelica.Math.sin` and expecting tools to magically treat this as the mathematical sine function would introduce an unnecessary dependency of the language specification on the MSL.
- Not having `sin` in the core language makes it awkward to express minimal examples without pulling in the entire MSL.
- One could put the implementation of `sin` in ModelicaServices, where it could be documented that this is the mathematical sine function, but this seems way too complicated compared to simply having it in the core language.

2020-11-18 07:41 UTC, sjoelund commented
> One could put the implementation of sin in ModelicaServices, where it could be documented that this is the mathematical sine function, but this seems way too complicated compared to simply having it in the core language.

One could also have it as a built-in function and still document it. We could have a ModelicaBuiltin.mo file or similar attached to the language specification, at least for functions with an interface that can be expressed as normal Modelica code. OpenModelica does something similar (but OpenModelica-specific things are also added to the file): [ModelicaBuiltin.mo](https://github.com/OpenModelica/OpenModelica/blob/v1.16.1/OMCompiler/Compiler/FrontEnd/ModelicaBuiltin.mo)

2021-01-19 21:57 UTC, beutlich commented
@henrikt-ma I forgot about this one when creating #3703. (Too many open PRs I am afraid.) Closing after #3703 got merged.

2021-01-19 21:57 UTC, closed without merging