Fix descriptions w.r.t. w_rel
modelica/ModelicaStandardLibrary pull request #3694
Opened 2020-12-22 20:37 UTC by beutlich

Remove reference on `w_rel` if there is no `w_rel` in component.

2021-01-25 09:34 UTC, tobolar requested changes
There also shall be used "tau" instead of "mu" in BearingFriction as the torque is given directly in tau_pos

2021-01-27 19:38 UTC, christiankral approved these changes
Looks OK from my understanding

2021-01-27 21:17 UTC, beutlich commented on Modelica/Mechanics/Rotational/Components/BearingFriction.mo
> +    "Signs for sliding friction coefficient table interpolation: [sign for w, sign for mu]";
Sure.

2021-01-28 09:40 UTC, tobolar approved these changes

2021-01-28 09:43 UTC, merged