Docker pull at Travis CI
modelica/ModelicaStandardLibrary pull request #3701
Opened 2021-01-01 15:59 UTC by beutlich

refs #3699: Try workaround from https://travis-ci.community/t/docker-hub-you-have-reached-your-pull-rate-limit/10517/6

2021-01-01 17:00 UTC, beutlich commented
@sjoelund Please advice!

2021-01-04 14:44 UTC, beutlich commented on .travis.yml
>    - docker pull openmodelica/openmodelica:v1.12.0-minimal
```suggestion
  - docker pull mirror.gcr.io/openmodelica/openmodelica:v1.12.0-minimal
```

2021-01-04 14:53 UTC, sjoelund requested changes
Google doesn't mirror all docker repos. Use docker login as documented by travis instead: https://docs.travis-ci.com/user/docker/#pushing-a-docker-image-to-a-registry

2021-01-04 14:59 UTC, beutlich commented on .travis.yml
> +  - docker pull mirror.gcr.io/openmodelica/openmodelica:v1.12.0-minimal
```suggestion
  - docker pull registry-1.travis-ci.com/openmodelica/openmodelica:v1.12.0-minimal
```

2021-01-04 20:43 UTC, beutlich commented
> 
> 
> Google doesn't mirror all docker repos. Use docker login as documented by travis instead: https://docs.travis-ci.com/user/docker/#pushing-a-docker-image-to-a-registry

I do not get the docker login working.

2021-01-06 08:59 UTC, beutlich commented
FYI: I am considering to (temporarily) remove the checks that require the openmodelica docker image. For the moparser docker image I am considering to make use of https://github.com/modelica-tools/ModelicaSyntaxChecker instead.

2021-01-14 17:09 UTC, closed without merging