Avoid "builtin" external language for common mathematical functions
modelica/ModelicaStandardLibrary pull request #3703
Opened 2021-01-05 22:09 UTC by beutlich

Modelica Language Specification 3.5 deprecates the usage of the "builtin" external language.

2021-01-05 22:29 UTC, henrikt-ma requested changes
These shouldn't be external functions at all.  Thereby, we don't assume mathematical understanding about all the functions you might find in external libraries.  Instead, these should just be wrappers around the elementary mathematical functions of the core language.

2021-01-06 14:41 UTC, beutlich commented
@henrikt-ma @HansOlsson There is now an infinite lookup recursion. Am I doing the right thing?

2021-01-06 20:25 UTC, henrikt-ma requested changes
As you noticed yourself, you need to use fully qualified references to the built-in functions:
```
y := .sin(u);
```

2021-01-06 20:55 UTC, henrikt-ma approved these changes
Looks good to me.

(I have a personal preference for outputs defined by binding equation since functions written in this form tend to be easier to reason about mathematically in general.)

2021-01-06 21:05 UTC, henrikt-ma commented
Actually, I'll withdraw my approval, since I'd like us to first discuss `Inline = true`.  Any reason this annotation shouldn't be used here?

2021-01-06 21:07 UTC, henrikt-ma reviewed
Actually, I'll withdraw my approval, since I'd like us to first discuss `Inline = true`.  Any reason this annotation shouldn't be used here?

2021-01-06 21:19 UTC, beutlich commented
> 
> 
> Actually, I'll withdraw my approval, since I'd like us to first discuss `Inline = true`. Any reason this annotation shouldn't be used here?

For one-line assignments the default inlining should be true, at least in Dymola and SimulationX.

2021-01-06 22:11 UTC, henrikt-ma commented
> For one-line assignments the default inlining should be true, at least in Dymola and SimulationX.

As far as I can tell, this isn't prescribed by the specification, so I don't really see why one shouldn't set `Inline = true`.  I'm requesting additional reviews to collect more opinions.  For me, a good resolution would be to leave out `Inline` here, combined with a specification issue about describing situations when `Inline = true` is default.

2021-01-07 14:12 UTC, eshmoylova approved these changes
Looks good to me. We would inline them the way they are written. But if other tools would prefer having `Inline = true` explicit I have to objections to that.

2021-01-07 14:35 UTC, sjoelund requested changes
I think I would prefer `Inline=true` explicitly added since it is possible to generate a diagnostic message if the tool fails to inline the call and in these cases if it fails, a tool that does not inline it also likely doesn't add an automatic derivative function. These functions are used quite a lot and adding the annotation makes it explicit that this must be inlined or results may be bad or performance poor.

2021-01-07 14:46 UTC, henrikt-ma commented
> I think I would prefer `Inline=true` explicitly added since it is possible to generate a diagnostic message if the tool fails to inline the call and in these cases if it fails, a tool that does not inline it also likely doesn't add an automatic derivative function. These functions are used quite a lot and adding the annotation makes it explicit that this must be inlined or results may be bad or performance poor.

So what did you think of instead making it a specification issue to allow simple functions like this to have `Inline = true` by default?  For example, we could state that all functions written in binding equation form would have `Inline = true` by default.

2021-01-07 14:54 UTC, sjoelund commented
> So what did you think of instead making it a specification issue to allow simple functions like this to have Inline = true by default? For example, we could state that all functions written in binding equation form would have Inline = true by default.

You'd need to make it with a binding equation and each input is used no more than once to make it sane to Inline in some tools. By making it explicit, Inline should be performed. The implicit one that it has a binding equation is just a hint that it might be good to inline this call.

2021-01-07 15:04 UTC, henrikt-ma commented
> You'd need to make it with a binding equation and each input is used no more than once to make it sane to Inline in some tools. By making it explicit, Inline should be performed. The implicit one that it has a binding equation is just a hint that it might be good to inline this call.

What I meant was to really really make `Inline = true` for functions expressed in some easily recognized ways.  Then, it would be just as wrong to not inline as when `Inline = true` is set explicitly.  I don't expect everybody to like this idea, I'm only trying to bring clarity to what people think of this approach.  I prefer this approach, since I think that there are many functions expressed in simple ways where the author intuitively assumes that it will be inlined, and therefore doesn't bother to add the `Inline` annotation, causing unnecessary room for unexpected differences across tools.

2021-01-07 15:08 UTC, henrikt-ma commented
> > You'd need to make it with a binding equation and each input is used no more than once to make it sane to Inline in some tools. By making it explicit, Inline should be performed. The implicit one that it has a binding equation is just a hint that it might be good to inline this call.
> 
> What I meant was to really really make `Inline = true` for functions expressed in some easily recognized ways. Then, it would be just as wrong to not inline as when `Inline = true` is set explicitly. I don't expect everybody to like this idea, I'm only trying to bring clarity to what people think of this approach. I prefer this approach, since I think that there are many functions expressed in simple ways where the author intuitively assumes that it will be inlined, and therefore doesn't bother to add the `Inline` annotation, causing unnecessary room for unexpected differences across tools.

The functions in this PR would all be possible to express in an extremely simple form:
```
  input Modelica.SIunits.Angle u;
  output Real y = sin(u);
```

These are some of the requirements they would fulfill:
- In binding equation form; no algorithm section.
- Every input only used once.
- Only a single output.

2021-01-07 15:11 UTC, beutlich commented
> I think I would prefer `Inline=true` explicitly added

Can do. I have no strong objection.

2021-01-07 22:14 UTC, henrikt-ma commented
Several more complicated functions in `Modelica.Math.Distributions` already have `Inline = true`, so the approach of not doing it here and expecting the specification to make it the default doesn't seem like a good option.  It would be better to set `Inline = true` now, then think about making it the default in the specification, and if it does, then adapt the MSL accordingly.

If the specification would end up only making `Inline = true` for functions in "binding equation form", it won't be a big deal to rewrite the functions in this form, so the current form with an algorithm containing a single assignment statement seems totally fine for now.

2021-01-08 07:07 UTC, sjoelund approved these changes

2021-01-08 07:10 UTC, henrikt-ma approved these changes

2021-01-12 08:55 UTC, HansOlsson approved these changes
Looks good. I realized that we in some rare cases will have to slightly modify Dymola to support these as efficiently as the previous variant, but that shouldn't be a blocker - and likely has other benefits.

2021-01-13 21:52 UTC, merged