Stable calculation of quaternion from transformation matrix
modelica/ModelicaStandardLibrary pull request #3724
Opened 2021-01-18 11:45 UTC by tobolar

Close #3588
(It could be possible to apply this to older version(s) as well.)

2021-01-18 19:14 UTC, beutlich commented on Modelica/Mechanics/MultiBody/Frames/Quaternions/from_T.mo
> +  Q := Q .* 0.5/sqrt(t);
```suggestion
  Q := Q*0.5/sqrt(t);
```
The component-wise multiplication is not relevant when multiplying by a scalar and made me wondering first.

2021-01-18 19:18 UTC, beutlich reviewed
Two more thoughts:

* Would be good to have your test model of #3588 in ModelicaTest as simple unit test.
* Maybe you could add a proper Documentation.revision annotation where you summarize the improvement and also link to the utilized source.

2021-01-19 14:04 UTC, tobolar commented
@beutlich Done.

2021-01-19 22:41 UTC, beutlich commented
> 
> 
> @beutlich Done.

I cleaned up the commit history.

2021-01-23 18:23 UTC, christiankral commented
I am afraid I cannot asses this issue.

2021-01-27 21:46 UTC, beutlich requested changes

2021-02-01 16:57 UTC, HansOlsson approved these changes
Looks good. I also like that the statement c1>=0, c2>=0 ... was removed; as it seems false.

2021-04-16 07:59 UTC, MartinOtter approved these changes

2021-05-27 19:40 UTC, beutlich commented
I rebased the PR branch to include the latest CI checks.

2021-06-04 07:40 UTC, merged