Fix interpretation of coefficients of complex transfer function
modelica/ModelicaStandardLibrary pull request #3733
Opened 2021-01-24 13:31 UTC by christiankral

Refs #3651

2021-02-21 10:01 UTC, AHaumer requested changes
Again we have the problem that the bugfix is not backwards compatible.
I'd suggest to:

- leave the old implementatio  unchanged and mark it as obsolete
- move Christian's implemenatition to a new block
- explain the situation in the documentation

2021-02-22 08:26 UTC, dietmarw commented
Also here my comment. If it is a bugfix then something was calculated wrongly before and need to be fixed. It would be very strange that we "fix" bugs by introducing new models and keep the buggy models around. That is if it is a clear bug and not just a different interpretation of the implementation.

2021-02-22 08:27 UTC, beutlich commented
I agree with @dietmarw here. Bugfixes shall be fixed in place and documented in the revision annotation. I also doubt that anyone used such a function if it was plainly wrong.

2021-03-08 17:10 UTC, christiankral commented
OK. The block will **not be renamed** and the bug fix will be implemented and documented.

2021-03-08 17:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/modelica/ModelicaStandardLibrary?pullRequest=3733) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/modelica/ModelicaStandardLibrary?pullRequest=3733) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: christiankral<br/>:x: Christian Kral<br/><hr/>**Christian Kral** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/modelica/ModelicaStandardLibrary?pullRequest=3733) it.</sub>

2021-03-08 17:16 UTC, christiankral commented
@beutlich Why is it asking again for signing the CLA? I just signed it at https://github.com/modelica/ModelicaStandardLibrary/pull/3742#issuecomment-792252602

2021-03-09 08:01 UTC, beutlich commented
> 
> 
> @beutlich Why is it asking again for signing the CLA? I just signed it at [#3742 (comment)](https://github.com/modelica/ModelicaStandardLibrary/pull/3742#issuecomment-792252602)

Because you (accidently ?) committed as `Christian Kral <christian@Yogix>`. I will squash all commits as one later.

2021-03-09 08:18 UTC, christiankral commented
> > @beutlich Why is it asking again for signing the CLA? I just signed it at [#3742 (comment)](https://github.com/modelica/ModelicaStandardLibrary/pull/3742#issuecomment-792252602)
> 
> Because you (accidently ?) committed as `Christian Kral <christian@Yogix>`. I will squash all commits as one later.

Thanks for the hint. This happened accidentally. For some reason my git `user.name` and `user.email` got lost...

2021-03-17 17:44 UTC, christiankral commented
@beutlich Thanks for fixing the merge conflict. On my opinion the performed changes look all good.

2021-03-17 18:29 UTC, beutlich commented on Modelica/ComplexBlocks/Examples/ShowTransferFunction.mo
> +  parameter Real d=0.01 "Damping coefficient in kg/s (not the damping ratio)";
Would it als work if physical units are used actually instead of type Real?

2021-05-01 18:13 UTC, AHaumer approved these changes

2021-05-23 10:12 UTC, christiankral commented
@HansOlsson Is it legal Modelica code to use different units in the elements of vector `a`? 

```modelica
  parameter Real d(unit = "kg/s")=0.01 "Damping coefficient in kg/s (not the damping ratio)";
  parameter Modelica.Units.SI.Mass m=0.2 "Mass in kg";
  parameter Modelica.Units.SI.TranslationalSpringConstant c=0.1 "Stiffness in N/m";
  parameter Real b[:]={-m} "Numerator polynomial coefficients {-m} of the transfer function";
  parameter Real a[:]={m,d,c} "Denominator polynomial coefficients {m,d,c} of the transfer function";
``` 

It, however, does check and simulate OK in Dymola.

2021-05-24 06:28 UTC, HansOlsson commented
> @HansOlsson Is it legal Modelica code to use different units in the elements of vector `a`?

Yes. Whether it is good style is another issue.

> ```modelica
>   parameter Real d(unit = "kg/s")=0.01 "Damping coefficient in kg/s (not the damping ratio)";
>   parameter Modelica.Units.SI.Mass m=0.2 "Mass in kg";
>   parameter Modelica.Units.SI.TranslationalSpringConstant c=0.1 "Stiffness in N/m";
>   parameter Real b[:]={-m} "Numerator polynomial coefficients {-m} of the transfer function";
>   parameter Real a[:]={m,d,c} "Denominator polynomial coefficients {m,d,c} of the transfer function";
> ```
> 
> It, however, does check and simulate OK in Dymola.

The specification does not make it illegal, and you could even explicitly create vectors with different unit elements in Modelica like: `parameter Real a[3](unit={"kg","kg/s","kg.s-2"});` although Dymola currently ignores the unit in that case.

2021-05-24 07:09 UTC, henrikt-ma commented
> The specification does not make it illegal, and you could even explicitly create vectors with different unit elements in Modelica like: `parameter Real a[3](unit={"kg","kg/s","kg.s-2"});` although Dymola currently ignores the unit in that case.

While the specification doesn't make it illegal today, we also know that the specification is rather incomplete when it comes to defining a system for unit handling that would give tools the necessary foundation to reject models with unclear/erroneous unit consistency.  Hence, I think one should at least be prepared that arrays with heterogenous unit could be something we'll be forced to drop support for once we take on unit checking more seriously.

If one really wants to do transfer functions with units in a future-proof way, I have no better idea than making a fixed order wrapper model with only scalar coefficients that takes care of all the units, with the actual dynamics internally implemented using a unit-less transfer function.

2021-05-24 16:04 UTC, christiankral commented
@beutlich I suggest to keep the implementation with `Real` parameters then.

2021-05-24 16:56 UTC, beutlich commented
A third option to unitless parameters or array with heterogenous unit would be something like:

```mo
parameter Real d(unit = "kg/s")=0.01 "Damping coefficient in kg/s (not the damping ratio)";
parameter Modelica.Units.SI.Mass m=0.2 "Mass in kg";
parameter Modelica.Units.SI.TranslationalSpringConstant c=0.1 "Stiffness in N/m";
final parameter oneReciprocalDamping(unit="s/kg") = 1;
final parameter oneReciprocalMass(unit="kg-1") = 1;
final parameter oneReciprocalSpringConstant(unit="m/N") = 1;
parameter Real a[:]={m*oneReciprocalMass, d*oneReciprocalDamping, c*oneReciprocalSpringConstant}
  "Unitless denominator polynomial coefficients {m,d,c} of the transfer function";
```
I think this is the cleanest Modelica can offer for now.
I also propose to utilize TranslationalDampingConstant for d.

2021-05-24 23:36 UTC, henrikt-ma commented
> I think this is the cleanest Modelica can offer for now.

Looks like a splendid place to use `final constant` instead of `final parameter`, doesn't it?

2021-05-25 05:43 UTC, beutlich commented
Right, here's a nicer proposa, inspired from https://github.com/modelica/ModelicaStandardLibrary/blob/39fe8050c0e7f487720d2f3ea5d91e25ef359ffe/Modelica/Electrical/Analog/Examples/Utilities/SwitchedCapacitor.mo#L29-L30:

```mo
  parameter Modelica.Units.SI.Mass m = 0.2 "Mass in kg";
  parameter Modelica.Units.SI.TranslationalDampingConstant d = 0.01 "Damping coefficient in kg/s (not the damping ratio)";
  parameter Modelica.Units.SI.TranslationalSpringConstant c = 0.1 "Stiffness in N/m";
protected
  constant Modelica.Units.SI.Mass oneKilogram = 1
    "Helping constant to satisfy unit check";
  constant Modelica.Units.SI.TranslationalDampingConstant oneUnitDampingConstant = 1
    "Helping constant to satisfy unit check";
  constant Modelica.Units.SI.TranslationalSpringConstant oneUnitSpringConstant = 1
    "Helping constant to satisfy unit check";
public
  final parameter Real a[:]={m/oneKilogram, d/oneUnitDampingConstant, c/oneUnitSpringConstant}
    "Unitless denominator polynomial coefficients {m,d,c} of the transfer function";
```

2021-05-25 06:45 UTC, henrikt-ma commented
> Right, here's a nicer proposa, inspired from

Yes, this is nicer.  Still, in principle, these constants should also be `final`, as they shouldn't even be modified in derived classes.  Of course, I can also see that the need for `final` is much bigger when dealing with public elements.

2021-05-31 19:32 UTC, christiankral commented
OK, I will implement @beutlich's proposal then.

2021-06-08 05:12 UTC, beutlich commented on Modelica/ComplexBlocks/Examples/ShowTransferFunction.mo
> +  final parameter Real b[:]={-m} "Numerator polynomial coefficients {-m} of the transfer function";
```suggestion
  final parameter Real b[:]={-m/oneUnitMass} "Unitless numerator polynomial coefficients {-m} of the transfer function";
```
Should `b` also be unitless?

2021-06-08 09:55 UTC, beutlich approved these changes

2021-11-12 20:37 UTC, beutlich reviewed
Please also update the table of critical errors in Modelica.UsersGuide.ReleaseNotes.Version_X_Y_0. Thanks.

2021-12-13 15:14 UTC, AHaumer approved these changes

2022-10-07 06:28 UTC, merged