Improve documentation of both rotational and translational sensors
modelica/ModelicaStandardLibrary pull request #3862
Opened 2021-09-08 15:24 UTC by tobolar

Esp. improve format of variables and Modelica code according to HTML documentation conventions.

2021-11-18 12:03 UTC, MartinOtter approved these changes

2021-11-20 22:15 UTC, christiankral requested changes
I suggest to move the calculation equation of the power sensors to the HTML documentation

2021-11-20 22:15 UTC, christiankral commented on Modelica/Mechanics/Translational/Sensors/PowerSensor.mo
> +  "Ideal sensor to measure the power between two flanges (= flange_a.f * der(flange_a.s))"
```suggestion
  "Ideal sensor to measure the power between two flanges"
```

2021-11-20 22:15 UTC, christiankral commented on Modelica/Mechanics/Translational/Sensors/PowerSensor.mo
> +Measures the <em>power</em>&nbsp;<var>P</var> between two flanges
```suggestion
Measures <code>power  = flange_a.f * der(flange_a.s)</code> between two flanges
```

2021-11-22 12:04 UTC, tobolar commented on Modelica/Mechanics/Rotational/Sensors/PowerSensor.mo
> +  "Ideal sensor to measure the power between two flanges (= flange_a.tau * der(flange_a.phi))"
Resolved in d71ceb225c03046a6f897f0640d52b935fd018e5

2021-11-22 12:50 UTC, tobolar commented on Modelica/Mechanics/Rotational/Sensors/PowerSensor.mo
> +Measures the <em>power</em>&nbsp;<var>P</var> between two flanges
> As the variableP is not used at all it makes no sense to refer to it.

This also concerns other sensors where a variable is always written. But I think we remove it there as well.

2021-11-22 14:25 UTC, tobolar commented on Modelica/Mechanics/Rotational/Sensors/PowerSensor.mo
> +Measures the <em>power</em>&nbsp;<var>P</var> between two flanges
Done in https://teamsites-extranet.dlr.de/ts/PT-Board-Strassenverkehr/GFPlanung%202022ff/3%20VuV4NGC%20(Methoden,%20Prozesse%20und%20Werkzeugketten%20f%C3%BCr%20die%20Validierung%20und%20Verifikation%20von%20NGC)/TP%207000/VorlageAnhangProjektplan_TP7000.docx?web=1

2021-11-22 14:26 UTC, tobolar commented on Modelica/Mechanics/Translational/Sensors/PowerSensor.mo
> +  "Ideal sensor to measure the power between two flanges (= flange_a.f * der(flange_a.s))"
Changed, see above.

2021-11-22 14:26 UTC, tobolar commented on Modelica/Mechanics/Translational/Sensors/PowerSensor.mo
> +Measures the <em>power</em>&nbsp;<var>P</var> between two flanges
Changed, see above.

2021-11-22 14:26 UTC, tobolar commented on Modelica/Mechanics/Rotational/Sensors/PowerSensor.mo
> +Measures the <em>power</em>&nbsp;<var>P</var> between two flanges
Done in 33b2ffad0d01ba0d012eded10b34f8686bbfe34d

2022-02-01 21:52 UTC, hubertus65 approved these changes
Looks all good.

2022-02-01 21:58 UTC, hubertus65 approved these changes

2022-02-01 21:58 UTC, hubertus65 approved these changes

2022-02-01 21:59 UTC, hubertus65 approved these changes

2022-02-01 22:01 UTC, merged