Fix release notes generation
modelica/ModelicaStandardLibrary pull request #3999
Opened 2022-06-20 18:58 UTC by beutlich

The previously used docverter service for MD to HTML/PDF conversion was shut down and will not come back. This is an alternative implementation with local MD to HTML conversion and utilizing the docraptor service for HTML to PDF conversion.

2022-06-20 19:22 UTC, beutlich commented
Here's the successful test run: https://github.com/beutlich/ModelicaStandardLibrary/actions/runs/2531080050

2022-06-23 08:54 UTC, dietmarw requested changes
I don't think relying (again) on a third-party service here is non-optimal. Why not run the PDF/HTML generation directly in the GH actions environment?

2022-07-04 18:39 UTC, beutlich commented
OK, we can wait until a new release is scheduled.

2024-01-14 09:13 UTC, beutlich commented
> OK, we can wait until a new release is scheduled.

@Harisankar-Allimangalath Since a new release is about to be scheduled we need to decide how to fix the release notes generation script. The proposed changes work for me as indicated by #4251 (though the free docraptor service only enables 5 documents per months w/o watermark).

2024-01-17 00:37 UTC, casella commented
@beutlich there are 2 weeks left until we branch off. Do you think you and @Harisankar-Allimangalath can fix it by then?

2024-01-17 06:29 UTC, beutlich commented
> @beutlich there are 2 weeks left until we branch off. Do you think you and @Harisankar-Allimangalath can fix it by then?

Since I already spent quite some time on this PR I see three short-term options for the next MSL release:

1. Accept as is (with the dependency on the docraptor service and their free plan of 5 watermark-free PDF documents per month). If it will break some day in future, well, let's revisit the topic by then.
2. Remove/disable the PDF generation, that is only deploy the Markdown and HTML files of the auto-generated release notes.
3. Remove the script (and CI trigger) from the repository, which does not mean, it can't be run from somewhere else.

2024-01-17 06:34 UTC, dietmarw approved these changes
I go for the pragmatic solution and go for "1. Accept as is".

2024-01-19 06:49 UTC, Harisankar-Allimangalath approved these changes

2024-01-19 06:50 UTC, merged