RotationalCoupling
modelica/ModelicaStandardLibrary pull request #4019
Opened 2022-08-05 07:47 UTC by AHaumer

Address #4012:
- Moved `RotationalCopling` to `Modelica.Electrical.Machines.Utilities`.
- Used `IdealGear(ratio=-1)` inside the coupling.
- Imrpoved documentation.

2022-09-05 12:58 UTC, dietmarw requested changes
I think this implementation is much cleaner. However, the comparisonSignals and test models introduced in #3786 should get removed/updated

2022-09-15 15:12 UTC, tobolar commented
I'm convinced with this solution. 

But sorry for bother you again - I'm still stumbling upon the icon. To me, it makes an impression of a jaw coupling (https://github.com/modelica/ModelicaStandardLibrary/issues/4012#issuecomment-1186856437) which in fact enables some very small relative rotation between the two flanges `a` and `b` - in fact, it is limited mechanically. 
In contrast, considering the example `Modelica.Electrical.Machines.Examples.DCMachines.DCPM_Drive`, the relative angle between the two machines `dcpm` reaches several hunderts of radian.

We have obviously different points of view - while I'm focused on that one component only, you consider the whole drive test rig. Located in the `Electrical` library now, consider this as my last comment on this component and feel free to design the icon on your own.

2022-09-27 13:40 UTC, christiankral commented
To have the coupling more obvious in the simulation example it would make sense to add two rotational speed sensors. The doumentation could then refer `speedSensor1.w` and `speedSensor2.w`.

2022-10-03 08:00 UTC, christiankral approved these changes
OK for me.

2025-03-01 18:49 UTC, casella commented
@AHaumer can you please take care of @dietmarw's [comment]([url](url)), so we can close this issue for the 4.1.0 release? Thanks!

2025-03-05 13:41 UTC, AHaumer commented
@casella sorry for the delay, dietmarw's concerns are addressed.

2025-03-05 14:12 UTC, dietmarw commented
@AHaumer I can not see that you actually updated the comparison signals. That still needs to get fixed.

2025-03-05 15:50 UTC, AHaumer commented
Please @dietmarw bei a little bit more specific.
Comparison signals both of Modelica and ModelicaTest contain coupling.{w, tau}. 
What do you want to be updated in the comparison signals?

2025-03-05 18:30 UTC, dietmarw commented
@AHaumer What where you trying to fix with your commit? Your commit fixed another bug of a wrong name reference.
but not the comparison signals, which need to be put in the place correlating with the place of where the coupling now resides. I.e., under Electrical.Machines.... That is what my comment was about.

2025-03-06 10:37 UTC, AHaumer commented
> @AHaumer What where you trying to fix with your commit? Your commit fixed another bug of a wrong name reference. but not the comparison signals, which need to be put in the place correlating with the place of where the coupling now resides. I.e., under Electrical.Machines.... That is what my comment was about.

One comparisonSignals.txt resides in \Modelica\Resources\Reference\Modelica\Electrical\Machines\Examples\DCMachines\DCPM_Drive, this is correct I suppose?
The other comparisonSignals.txt resides in \ModelicaTest\Resources\Reference\ModelicaTest\Rotational\AllComponents, which matches the structure of the models.
Would you like to shift the part with the coupling from ModelicaTest.Rotational.AllComponents to an own test example in ModelicaTest.Electrical.Machines or to remove this part completely from AllComponents and from the matching comparionsSignals? What's the harm if it remains as it is?

2025-03-06 14:56 UTC, casella commented
@AHaumer since the RotationalCoupling model was moved from Modelica.Mechanics.Rotational to Modelica.Electrical.Machines.Utilities, I guess it makes sense that the corresponding test model is moved from ModelicaTest.Rotational.AllComponents to ModelicaTest.Electrical.Machines, since the coupling model now belongs to Electrical.Machines instead of Mechanical.Rotational.

That also requires to update the referenceSignals.txt of AllComponents, because some components will be removed from that model.

2025-03-06 16:15 UTC, dietmarw commented
Thanks @casella for the clarification. That is exactly what the issue is.

2025-03-06 19:03 UTC, AHaumer commented
Ok since the component is tested in Modelica.Electrical.Machines.Examples.DCMachines.DCPM_Drive, 
I'll remove it from ModelicaTest.Rotational.AllComponents and of course the corresponding comparisonSignals.

2025-03-08 18:55 UTC, casella approved these changes
LGTM

2025-03-08 20:27 UTC, dietmarw approved these changes

2025-03-08 20:27 UTC, merged

2025-03-10 07:09 UTC, MatthiasBSchaefer commented
This PR needs a back-port to maint/4.1.x

2025-03-10 09:01 UTC, Esther-Devakirubai commented
Backported by #4584