Fix for #3971.
modelica/ModelicaStandardLibrary pull request #4074
Opened 2023-02-22 16:53 UTC by christoff-buerger

Fix for #3971: Moved the parameters into the interface. I double checked that all interface implementations (subclasses) in fact introduce both parameters; their defaults have been the same.

2023-02-22 18:50 UTC, beutlich requested changes

2023-02-22 18:50 UTC, beutlich commented on Modelica/Clocked/RealSignals/Interfaces/PartialNoise.mo
> +<p><span style=\"font-family: Arial;\">Interface block for uniformly distributed noise in some range noiseMin&nbsp;&hellip;&nbsp;noiseMax applied to a clocked Real input signal; the resulting noisy s
```suggestion
<p>Interface block for uniformly distributed noise in some range noiseMin&nbsp;&hellip;&nbsp;noiseMax applied to a clocked Real input signal; the resulting noisy signal is provided as clocked Real output signal.</p>
```

2023-02-23 08:56 UTC, HansOlsson commented
Hm... I did suggest that solution, and it makes sense - but it is a bit inconsistent since for non-clocked signals Modelica.Blocks.Interfaces.PartialNoise is inherited by Modelica.Blocks.Noise.UniformNoise which is unlimited.

If we think that is a problem we could have PartialRangeLimitedNoise as a separate base-class containing these parameters in both cases.

2023-02-23 08:56 UTC, HansOlsson approved these changes
I think this makes sense, and have suggested an alternative if we want to have more consistent interfaces.

2023-02-23 23:54 UTC, christoff-buerger commented
> Hm... I did suggest that solution, and it makes sense - but it is a bit inconsistent since for non-clocked signals Modelica.Blocks.Interfaces.PartialNoise is inherited by Modelica.Blocks.Noise.UniformNoise which is unlimited.
> 
> If we think that is a problem we could have PartialRangeLimitedNoise as a separate base-class containing these parameters in both cases.

Yes, we can do that; I have been aware of this alternative when pushing the current proposal. My thinking was along the lines, that such an additional base-class for even more variety can be done if there is any need at hand (hence, users request); I don't want to model too much that likely is never used as far as we can see.

2023-03-07 11:39 UTC, merged