Fix unit error in RobotR3.OneAxis
modelica/ModelicaStandardLibrary pull request #4108
Opened 2023-04-05 20:09 UTC by henrikt-ma

2023-04-06 08:25 UTC, tobolar requested changes

2023-04-06 08:25 UTC, tobolar commented on Modelica/Mechanics/MultiBody/Examples/Systems/RobotR3/OneAxis.mo
> +  parameter SI.Length rg = sqrt(1.3) "Radius of gyration of load";
`SI.Radius` would fit better here since rg>=0 m.

2023-04-06 09:26 UTC, henrikt-ma commented on Modelica/Mechanics/MultiBody/Examples/Systems/RobotR3/OneAxis.mo
> +  parameter SI.Length rg = sqrt(1.3) "Radius of gyration of load";
OK.  Done.  Resolving.

2023-04-06 16:45 UTC, hubertus65 approved these changes

2023-04-11 07:20 UTC, HansOlsson commented
Hmm... Two related questions:

- Is "radius of gyration" clear enough as description?
- Is there some corresponding "area" that we can use to avoid taking the square-root and then squaring it?

2023-04-11 07:43 UTC, tobolar commented
> Is "radius of gyration" clear enough as description?

I think "radius of gyration" is fine and known in the corrsponding theory (even if I personally forgot it years ago :-O ). An internet search also responds sufficient related stuff.

> Is there some corresponding "area" that we can use to avoid taking the square-root and then squaring it?

Not sure about this. A solution could be to take a value of radius of gyration close to sqrt(1.3), such as e.g. 1.14 m. This would lead to changes of load's inertia `load.J` of 0.03 %. Probably this would even be within the tolerance or regression checks.

2023-04-17 08:41 UTC, henrikt-ma commented
> > Is there some corresponding "area" that we can use to avoid taking the square-root and then squaring it?
> 
> Not sure about this. A solution could be to take a value of radius of gyration close to sqrt(1.3), such as e.g. 1.14 m. This would lead to changes of load's inertia `load.J` of 0.03 %. Probably this would even be within the tolerance or regression checks.

Sounds good to me.  @tobolar, @HansOlsson, @hubertus65, @MartinOtter, please react to this comment with thumb up or thumb down as an indication of whether to go with 1.14.

2023-10-27 19:07 UTC, hubertus65 approved these changes

2023-11-01 07:01 UTC, Harisankar-Allimangalath commented
@MartinOtter can you please reply to @henrikt-ma  and do the pending review , Thankyou

2023-11-02 12:11 UTC, henrikt-ma commented
I acted on the current reactions to https://github.com/modelica/ModelicaStandardLibrary/pull/4108#issuecomment-1510939157, which where 3/3 thumbs up, and with this I hope that this is now ready to be merged.

2023-11-06 10:39 UTC, tobolar commented
> ...  I hope that this is now ready to be merged.

I fully agree. We have two positive reviews and could merge.

2023-11-14 12:43 UTC, merged