Fix unit error in Thyristor
modelica/ModelicaStandardLibrary pull request #4119
Opened 2023-04-17 12:53 UTC by qlambert-pro

Introduces a variable to resolve a unit error in an equation.

We should give a better name to the variable I have introduced.

2023-04-27 16:26 UTC, AHaumer requested changes
I'm not the author of this model, and I don't know the meaning of "vRef = 0.65". 
It might be better to search for a name explaining the nature of it, and to declare it either as (maybe protected) constant or as a parameter.
@christophclauss can you tell us more about this "secret value"?

2023-04-28 05:48 UTC, HansOlsson commented
>BTW, I can't figure out why a tool should issue a unit error? Isn't it possible to deduce that "0.65" is a constant whose quantity is voltage? @HansOlsson or othe friends from Map-Lang could you please comment on this?

There are two parts to that answer:
- The problematic part is `0.65^2/VGT` or `vRef^2/VGT`; the other uses of 0.65 should be allowed by the 4-line proposal. The `a=0.65*b;` are exactly the kind of equations that the proposal aims to use unit-checking to help detect errors in.
- If there were a constant with value 0.65 we could in fact deduce its unit, but we obviously cannot assume that all 0.65 have the same unit; but having a "Real vRef=0.65;" and deducing its unit seems weird.

2023-05-02 13:59 UTC, henrikt-ma commented
> * If there were a constant with value 0.65 we could in fact deduce its unit, but we obviously cannot assume that all 0.65 have the same unit; but having a "Real vRef=0.65;" and deducing its unit seems weird.

I'll just expand slightly on this.  In the unit handling discussions at the last physical language meeting, there was some sort of vague conclusion that we should probably deprecate declaring constants without explicit `unit`.  This would make it easier to reason about a the constants in Modelica libraries, as they would always have the same unit regardless of application.  Also, since a package constant doesn't need to belong to an instance, we avoid the problem of having inferred a unit for something which isn't present in the translated model (and hence is difficult to communicate to the user).

2023-11-14 14:37 UTC, hubertus65 approved these changes
By decision on 2023-11-14

2023-11-14 14:38 UTC, hubertus65 commented
> I'm not the author of this model, and I don't know the meaning of "vRef = 0.65". It might be better to search for a name explaining the nature of it, and to declare it either as (maybe protected) constant or as a parameter. @christophclauss can you tell us more about this "secret value"? BTW, I can't figure out why a tool should issue a unit error? Isn't it possible to deduce that "0.65" is a constant whose quantity is voltage? @HansOlsson or othe friends from Map-Lang could you please comment on this?

I think your questions have been addressed, please re-review and approve, @AHaumer

2023-11-15 09:11 UTC, HansOlsson commented
I haven't added reviewed this - so I will just comment.

As far I understand 0.65V is a common "Forward threshold" or knee-voltage for Silicon diodes (well 0.6V to 0.7V); I assume Thyristor have some electrical similarities to diodes, but it was a long time since I took those courses.

Thus I don't know an appropriate name if `vRef` isn't good enough. 

BTW: It is plausible that changing just that value makes sense for other materials, but I don't know. That will impact whether it should be a public non-final parameter or not.

2023-11-15 10:30 UTC, HansOlsson commented on Modelica/Electrical/Analog/Semiconductors/Thyristor.mo
> +  SI.Voltage vRef = 0.65;
```suggestion
  parameter SI.Voltage vRef = 0.65;
```
Or possibly constant, or final parameter.
Having a normal variable with binding is kind of unusual.

2023-12-13 15:35 UTC, christiankral commented
> BTW: It is plausible that changing just that value makes sense for other materials, but I don't know. That will impact whether it should be a public non-final parameter or not.

Even though I am not familiar with the transistor model I would rather go for a `final parameter`. If there is a need for a public parameter, we can change it at any time in a backwards compatible way.

2024-01-10 15:00 UTC, AHaumer approved these changes
Fine with me

2024-01-14 13:16 UTC, merged