Implemented ie.start
modelica/ModelicaStandardLibrary pull request #4269
Opened 2024-01-16 18:14 UTC by AHaumer

implemented start value for ie (excitation current) of electrical excited synchronous machine (Electrical,Machines and Magnetic.FundamentalWave) as requested in #4242

2024-01-16 21:13 UTC, christiankral approved these changes
This is a fully backwards compatible change. So this is good.

2024-01-16 21:16 UTC, beutlich commented on Modelica/Electrical/Machines/Examples/SynchronousMachines/SMEE_LoadDump.mo
> +      points={{-19,80},{-10,80},{-10,61.3333}},
Is the pixel change intentional?

2024-01-16 21:16 UTC, beutlich commented on Modelica/Electrical/Machines/Examples/SynchronousMachines/SMEE_LoadDump.mo
> +      points={{-19,80},{-10,80},{-10,62.6667}},
Is the pixel change intentional?

2024-01-17 06:20 UTC, dietmarw commented
Since feature freeze for 4.1.0 was last Friday, I guess this will have to wait for the release after that.

2024-01-17 06:24 UTC, dietmarw requested changes, later dismissed
Wait until 4.2.0 see also https://github.com/modelica/ModelicaStandardLibrary/wiki/MSL-v4.1.0-release

2024-01-18 08:35 UTC, casella commented
@AHaumer this is really a minor fix, so it's not a big deal, but I'd prefer that we stick to the rules we gave ourselves: after Jan 12 we should only try to close pending PRs for 4.1.0 (there are plenty), not opening other ones. Thanks!

2026-02-16 11:28 UTC, AHaumer commented on Modelica/Electrical/Machines/Examples/SynchronousMachines/SMEE_LoadDump.mo
> +      points={{-19,80},{-10,80},{-10,62.6667}},
no. corrected. please re-review.

2026-02-16 12:54 UTC, dietmarw approved these changes

2026-02-16 12:54 UTC, merged