Restore ModelicaUtilities.h
modelica/ModelicaStandardLibrary pull request #4487
Opened 2024-10-21 19:12 UTC by beutlich

2024-10-24 11:53 UTC, henrikt-ma commented on Modelica/Utilities/Streams.mo
> -    external "C" ModelicaError(string) annotation(Include="#include \"ModelicaUtilities.h\"", Library="ModelicaExternalC");
At the moment, it is a tool responsibility to ensure `#include "ModelicaUtilities.h"` will find the file, so doesn't this change belong in a separate discussion about how Modelica external functions should point to _ModelicaUtilities.h_?

2024-10-24 12:00 UTC, henrikt-ma commented on .CI/Test/Common.c
> +#include "../../Modelica/Resources/C-Sources/ModelicaUtilities.h"
(Attaching comment to one of several possible places.)

Considering that _ModelicaUtilities.h_ has prototypes for functions that should be provided by the tool, and not for functions provided by the MSL, wouldn't a mode natural location be inside ModelicaServices?
```suggestion
#include "../../ModelicaServices/Resources/Include/ModelicaUtilities.h"
```

(Also note the use of the default include directory for the library.)

2024-10-24 12:21 UTC, henrikt-ma reviewed
If we are now to reintroduce the file in the MSL, I expect it to be taken as an indication of how other libraries should also deal with the need to find the file when building their external code.

One of the concerns behind the earlier decision to not include _ModelicaUtilities.h_ with the MSL was that the file is tied to a version of the language specification.  This isn't really a problem for the MSL, since the MSL is verbally tied to a language version:
> It is fully compliant to <a href=\"https://specification.modelica.org/maint/3.6/MLS.html\">Modelica Specification version 3.6</a> and it has been tested with Modelica tools from different vendors.

but becomes a problem if other libraries that may not even have any dependency on the MSL start making copies of the file.

Is this something to consider for this PR, or a concern to address in future work?

2024-10-24 15:42 UTC, casella commented
I had a closer look at this PR, but it contains a lot more that what I proposed in #4484.

The requirement in #4484 is to have a .h file only containing the definitions of the functions found in [Section 12.9.6](https://specification.modelica.org/maint/3.6/functions.html#utility-functions), to be used by people writing external functions that need to call ModelicaUtilities functions. Nothing more than that. Just a courtesy so you don't have to copy-and-paste from the specification.

This file is not meant to help building MSL external function libraries. BTW, we agreed that we won't even add them to the repo starting from the next version, as it is the tool vendor's responsibility to provide them.

2024-10-24 15:49 UTC, casella commented
Note that the MSL is standard, _but not tool agnostic_, it is well understood that each tool vendor needs to adapt it to its tool (implementing ModelicaServices low-level functions, compiling the tables C code, etc.) for a number of good reasons. What is standard are the interfaces, but not the implementations. 

Adapting the MSL to a specific tool is a burden of each tool vendor, that needs to do it once for its own tool, which is OK. What we want to avoid is to give _other library_ developers the burden of developing N versions of their libraries, one for each tool. Of course they should be able to just release one that works everywhere. The MA-provided ModelicaUtilities.h file simply fulfills this purpose.

2024-10-24 15:50 UTC, casella commented
> Considering that `ModelicaUtilities.h` has prototypes for functions that should be provided by the tool, and not for functions provided by the MSL, wouldn't a mode natural location be inside ModelicaServices?

This seems to me a good argument.

2024-10-24 15:55 UTC, beutlich commented
> I had a closer look at this PR, but it contains a lot more that what I proposed in #4484.

Yes, that's why I called it _restoration_.

Actually, the qualifiers for noreturn or format are really useful. I would not agree on a plain ModelicaUtilities.h without them. Why would we give up on such valuable purpose by design?

2024-10-24 23:57 UTC, casella commented
> > I had a closer look at this PR, but it contains a lot more that what I proposed in #4484.
> 
> Yes, that's why I called it _restoration_.
> 
> Actually, the qualifiers for noreturn or format are really useful. I would not agree on a plain ModelicaUtilities.h without them. 

Agreed. In that case, we should also update what we wrote in the MLS, otherwise that would be weird. In fact, the MLS could remain as it is, with a footnote like: these are conceptual definitions, please see the ModelicaConstants.h in ModelicaServices/Resources for more detail. Or something like that.

Do you agree?

2024-10-25 06:25 UTC, henrikt-ma commented
> Agreed. In that case, we should also update what we wrote in the MLS, otherwise that would be weird. In fact, the MLS could remain as it is, with a footnote like: these are conceptual definitions, please see the ModelicaConstants.h in ModelicaServices/Resources for more detail. Or something like that.

Isn't it standard procedure in the C/C++ world to have this sort of difference between how the prototypes are presented in documentation and what they actually look like in a header from the real world?

2024-10-25 07:43 UTC, henrikt-ma commented
Not so sure about my own suggestion with Modelica URIs here… Would we really want to encourage a solution where the ugly practice of implementations contained in `Include`-annotations should have the following annotation in order to find _ModelicaUtilities.h_?
```
IncludeDirectory="modelica://ModelicaServices/Resources/Include"
```
It both seems inconvenient for the library author, and means that tools that – for reasons I can't really understand – would like to use their own _ModelicaUtilities.h_ would need overwrite the file inside ModelicaServices.

If we had standardized the use of CMake for external code build projects, I would have proposed to explore the idea of relying on `MODELICA_PATH` for locating the correct directory to put in the include path.  Imagine an MA-provided CMake function to be called with a MSL (not MLS) version:
```
include_directory_for_ModelicaServices("4.1.0");
```
Since most Modelica libraries are made to work with the MSL anyways, it doesn't seem like a too strong assumption that their build projects would be ready to point to a specific version of the MSL for finding _ModelicaUtilities.h_.  A side effect of this is that since the MSL is made for a specific version of the MLS, this way of locating _ModelicaUtilities.h_ is indirectly locating the _ModelicaUtilities.h_ for that specific version of the MLS.

Based on this, I would prefer to _not_ start making _general_ use of Modelica URIs for locating _ModelicaUtilities.h_ or its parent directory.   Something _specific_ like this could serve us better:
> Newer versions of the Modelica Standard Library include a _ModelicaUtilities.h_ corresponding to the used version of the Modelica Language Specification, located at _modelica:/ModelicaServices/Resources/Include/ModelicaUtilities.h_. In principle, when combined with the `MODELICA_PATH`, this allows external code build projects to determine an include directory for _ModelicaUtilities.h_ based on a choice of version for the Modelica library.
> _[Milage may vary with how `MODELICA_PATH` is handled.]_

2025-02-14 09:41 UTC, HansOlsson commented on Modelica/Utilities/Streams.mo
> +    external "C" ModelicaError(string) annotation(IncludeDirectory="modelica://Modelica/Resources/C-Sources", Include="#include \"ModelicaUtilities.h\"", Library="ModelicaExternalC");
I would prefer that we don't change this line. 
The function should work without it, and the problem is that we might get a conflict between different ModelicaUtilities.h in tools with this change (in complicated models combining this with other functions).
Apart from that I'm in favor of the PR.

2025-02-14 09:46 UTC, HansOlsson commented on .CI/Test/Common.c
> +#include "../../Modelica/Resources/C-Sources/ModelicaUtilities.h"
As indicated in another place I think that proposed change would add some unnecessary problems; basically tools have to replace ModelicaServices with their own version - but we don't want to change the ModelicaUtilities.h used for building the libraries, or used for building other external libraries.
(Originally I also thought it might be a good idea, but I changed.)

2025-03-03 07:44 UTC, HansOlsson requested changes
I still think that the change of include-directories for the error function is unneeded, and might cause problems.

I realized that I only made that comment here, and not in other PR so it was merged without considering that change.

2025-03-03 09:11 UTC, henrikt-ma commented on Modelica/Utilities/Streams.mo
> +    external "C" ModelicaError(string) annotation(IncludeDirectory="modelica://Modelica/Resources/C-Sources", Include="#include \"ModelicaUtilities.h\"", Library="ModelicaExternalC");
I am also against changing this.  Since the relevant include directive is inside an `Include`-annotation, it is a tool responsibility to set up an include path with _ModelicaUtilities.h_.

As I understand it, it is currently not possible to use a Modelica URI for locating _ModelicaUtilities.h_ where it is really needed, that is, when setting up a build system (CMake, for instance) for a library to be built without a Modelica tool providing an include path with _ModelicaUtilities.h_.  A Modelica URI is then only a clean way of describing for the human library author where the file can be found, so that it can be copied to a suitable directory within author's library (where it should be found using relative directory paths, not a Modelica URI).

Finally, since I am not convinced that the Modelica library is a good home for a file directly coupled to the Modelica specification, I am also generally skeptical about spreading the use of _modelica:/Modelica/Resources/C-Sources_ as a way of describing where _ModelicaUtilities.h_ can be found.  (I would have been fine with _modelica:/ModelicaServices/Resources/Include_, since ModelicaServices is already entangled with the Modelica specification.)

2025-03-04 08:31 UTC, HansOlsson commented
> > I still think that the change of include-directories for the error function is unneeded, and might cause problems.
> 
> It is restored as it was before. No side-effect changes have been applied.
> 
> As mentioned before, it will be resolved by #4496 differently.

But when I look at the changed files I see a change in Streams.mo?

2025-03-04 16:17 UTC, beutlich commented
> But when I look at the changed files I see a change in Streams.mo?

I have to admit I cannot follow. It is a back-and-forth change: 1bb1d40d50ee1547d0c052babb6f099bb87f0362 changed it (and never was released in any official non-pre MSL). This PR reverts this change. That's what I call restoration (of the exact previous state).

2025-03-04 16:23 UTC, HansOlsson commented
> > But when I look at the changed files I see a change in Streams.mo?
> 
> I have to admit I cannot follow. It is a back-and-forth change: [1bb1d40](https://github.com/modelica/ModelicaStandardLibrary/commit/1bb1d40d50ee1547d0c052babb6f099bb87f0362) changed it (and never was released in any official non-pre MSL). This PR reverts this change. That's what I call restoration (of the exact previous state).

Now I understand. My concern was the specific line in Streams.mo; all the other changes were good.

If this PR is just restoring the previous state I agree that it makes sense to just merge it, even if it leads to a somewhat problematic line - provided we then clean up that.

2025-03-04 16:28 UTC, HansOlsson approved these changes
Ok. Just have this do the reversion and have the discussion about Streams.error in https://github.com/modelica/ModelicaStandardLibrary/pull/4496

2025-03-04 23:11 UTC, casella commented on .CI/Test/Common.c
> +#include "../../Modelica/Resources/C-Sources/ModelicaUtilities.h"
As per discussion during the [MAP-Lib meeting of 25/02/25](https://github.com/modelica/MA-Internal/blob/master/MA-Projects/MAP-LIB/MeetingMinutes/20250225-Monthly/README.md#pending-issues), we keep it Modelica/Sources/C-Sources. This make it clear that it's just a place where John Doe can look for the source code of the ModelicaUtilities headers when he needs it.

2025-03-04 23:20 UTC, casella commented on Modelica/Utilities/Streams.mo
> +    external "C" ModelicaError(string) annotation(IncludeDirectory="modelica://Modelica/Resources/C-Sources", Include="#include \"ModelicaUtilities.h\"", Library="ModelicaExternalC");
We already took a decision during the MAP-Lib meeting on 25/02/25, see the [minutes](https://github.com/modelica/MA-Internal/blob/master/MA-Projects/MAP-LIB/MeetingMinutes/20250225-Monthly/README.md#pending-issues). The decision was to merge #4535 on master, which implemented during the meeting.

I think we shouldn't now re-start again the discussion on what is the best place for the ModelicaUtilities.h file when back-porting this to the 4.1.0 branch. Let's just go ahead with what we already decided and have Thomas implement it also on the 4.1.0 branch.

2025-03-04 23:23 UTC, casella approved these changes
LGTM, it will be followed by #4496 to get the wanted behaviour.

2025-03-04 23:24 UTC, casella commented on Modelica/Utilities/Streams.mo
> -    external "C" ModelicaError(string) annotation(Include="#include \"ModelicaUtilities.h\"", Library="ModelicaExternalC");
#4496 will take care of that.

2025-03-04 23:26 UTC, merged